cabal-version: 1.12

name:           Util
version:        0.1.0.0
description:    Please see the README on GitHub at <https://github.com/KentuLiveAccount/HaMaze.Stack#readme>
homepage:       https://github.com/KentuLiveAccount/HaMaze.Stack#readme
bug-reports:    https://github.com/KentuLiveAccount/HaMaze.Stack/issues
author:         Kentaro Urata
maintainer:     kentuliveaccount@live.com
copyright:      2023 Kentaro Urata
license:        BSD3
license-file:   LICENSE
build-type:     Simple
extra-source-files:
  - README.md
  - CHANGELOG.md

source-repos:
 - type: git
 - location: ttps://github.com/KentuLiveAccount/HaMaze.Stack

library:
  exposed-modules:
    - Utils
  other-modules:
    - Paths_Util
  hs-source-dirs:
    - src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
  build-depends:
    - base >= 4.7 && < 5
    - containers == 0.6.5.1
    - array == 0.5.4.0
    - mtl == 2.2.2
    - Win32 == 2.12.0.1

default-language: Haskell2010